/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.    
 */

package org.apache.tuscany.sca.host.corba.testing.general;

/**
* org/apache/tuscany/sca/host/corba/testing/general/_TestInterfaceImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from general_tests.idl
* ¶roda, 25 czerwiec 2008 16:19:44 CEST
*/

public abstract class _TestInterfaceImplBase extends org.omg.CORBA.portable.ObjectImpl implements
    org.apache.tuscany.sca.host.corba.testing.general.TestInterface, org.omg.CORBA.portable.InvokeHandler {

    // Constructors
    public _TestInterfaceImplBase() {
    }

    private static java.util.Hashtable _methods = new java.util.Hashtable();
    static {
        _methods.put("getInt", new java.lang.Integer(0));
    }

    public org.omg.CORBA.portable.OutputStream _invoke(String $method,
                                                       org.omg.CORBA.portable.InputStream in,
                                                       org.omg.CORBA.portable.ResponseHandler $rh) {
        org.omg.CORBA.portable.OutputStream out = null;
        java.lang.Integer __method = (java.lang.Integer)_methods.get($method);
        if (__method == null)
            throw new org.omg.CORBA.BAD_OPERATION(0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

        switch (__method.intValue()) {
            case 0: // org/apache/tuscany/sca/host/corba/testing/general/TestInterface/getInt
            {
                int arg = in.read_long();
                int $result = (int)0;
                $result = this.getInt(arg);
                out = $rh.createReply();
                out.write_long($result);
                break;
            }

            default:
                throw new org.omg.CORBA.BAD_OPERATION(0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
        }

        return out;
    } // _invoke

    // Type-specific CORBA::Object operations
    private static String[] __ids = {"IDL:org/apache/tuscany/sca/host/corba/testing/general/TestInterface:1.0"};

    public String[] _ids() {
        return (String[])__ids.clone();
    }

} // class _TestInterfaceImplBase
