/**
 *
 *  Copyright 2005 The Apache Software Foundation or its licensors, as applicable.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package org.apache.tuscany.tools.java2wsdl.generate;


/**
 * This class provides a higher level abstraction to parts of the WSDL model
 * generated by Axis to enable easy and straight forward access to these parts
 * when the Tuscany Java2WSDL is applying fixes to the model.
 * 
 */
public class WSDLModel 
{
	//this class is to be populated later after identifying requirements for it.
}
