package org.apache.tuscany.tools.java2wsdl.generate;


/**
 * This class provides a higher level abstraction to parts of the WSDL model
 * generated by Axis to enable easy and straight forward access to these parts
 * when the Tuscany Java2WSDL is applying fixes to the model.
 * 
 */
public class WSDLModel 
{
	//this class is to be populated later after identifying requirements for it.
}
