/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.    
 */
package org.apache.tuscany.sca.binding.corba.testing.arrays_unions;


/**
* org/apache/tuscany/sca/binding/corba/testing/arrays_unions/RichUnion.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from arrays_unions.idl
*/

public final class RichUnion implements org.omg.CORBA.portable.IDLEntity
{
  private int ___x;
  private float ___y;
  private String ___z;
  private org.apache.tuscany.sca.binding.corba.testing.arrays_unions.InnerUnion ___iu;
  private boolean ___a;
  private int __discriminator;
  private boolean __uninitialized = true;

  public RichUnion ()
  {
  }

  public int discriminator ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    return __discriminator;
  }

  public int x ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    verifyx (__discriminator);
    return ___x;
  }

  public void x (int value)
  {
    __discriminator = 1;
    ___x = value;
    __uninitialized = false;
  }

  public void x (int discriminator, int value)
  {
    verifyx (discriminator);
    __discriminator = discriminator;
    ___x = value;
    __uninitialized = false;
  }

  private void verifyx (int discriminator)
  {
    if (discriminator != 1)
      throw new org.omg.CORBA.BAD_OPERATION ();
  }

  public float y ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    verifyy (__discriminator);
    return ___y;
  }

  public void y (float value)
  {
    __discriminator = 2;
    ___y = value;
    __uninitialized = false;
  }

  public void y (int discriminator, float value)
  {
    verifyy (discriminator);
    __discriminator = discriminator;
    ___y = value;
    __uninitialized = false;
  }

  private void verifyy (int discriminator)
  {
    if (discriminator != 2)
      throw new org.omg.CORBA.BAD_OPERATION ();
  }

  public String z ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    verifyz (__discriminator);
    return ___z;
  }

  public void z (String value)
  {
    __discriminator = 3;
    ___z = value;
    __uninitialized = false;
  }

  public void z (int discriminator, String value)
  {
    verifyz (discriminator);
    __discriminator = discriminator;
    ___z = value;
    __uninitialized = false;
  }

  private void verifyz (int discriminator)
  {
    if (discriminator != 3)
      throw new org.omg.CORBA.BAD_OPERATION ();
  }

  public org.apache.tuscany.sca.binding.corba.testing.arrays_unions.InnerUnion iu ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    verifyiu (__discriminator);
    return ___iu;
  }

  public void iu (org.apache.tuscany.sca.binding.corba.testing.arrays_unions.InnerUnion value)
  {
    __discriminator = 4;
    ___iu = value;
    __uninitialized = false;
  }

  public void iu (int discriminator, org.apache.tuscany.sca.binding.corba.testing.arrays_unions.InnerUnion value)
  {
    verifyiu (discriminator);
    __discriminator = discriminator;
    ___iu = value;
    __uninitialized = false;
  }

  private void verifyiu (int discriminator)
  {
    if (discriminator != 4)
      throw new org.omg.CORBA.BAD_OPERATION ();
  }

  public boolean a ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    verifya (__discriminator);
    return ___a;
  }

  public void a (boolean value)
  {
    __discriminator = -2147483648;
    ___a = value;
    __uninitialized = false;
  }

  public void a (int discriminator, boolean value)
  {
    verifya (discriminator);
    __discriminator = discriminator;
    ___a = value;
    __uninitialized = false;
  }

  private void verifya (int discriminator)
  {
    if (discriminator == 1 || discriminator == 2 || discriminator == 3 || discriminator == 4)
      throw new org.omg.CORBA.BAD_OPERATION ();
  }

} // class RichUnion
