package org.apache.tuscany.sca.binding.corba.testing.arrays_unions;

/**
* org/apache/tuscany/sca/binding/corba/testing/arrays_unions/TestStructHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from arrays_unions.idl
* niedziela, 17 sierpieñ 2008 15:45:39 CEST
*/

public final class TestStructHolder implements org.omg.CORBA.portable.Streamable
{
  public org.apache.tuscany.sca.binding.corba.testing.arrays_unions.TestStruct value = null;

  public TestStructHolder ()
  {
  }

  public TestStructHolder (org.apache.tuscany.sca.binding.corba.testing.arrays_unions.TestStruct initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.apache.tuscany.sca.binding.corba.testing.arrays_unions.TestStructHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.apache.tuscany.sca.binding.corba.testing.arrays_unions.TestStructHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.apache.tuscany.sca.binding.corba.testing.arrays_unions.TestStructHelper.type ();
  }

}
