<?xml version="1.0" encoding="ASCII"?>
<!--
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.    
-->
<module xmlns="http://www.osoa.org/xmlns/sca/0.9" xmlns:v="http://www.osoa.org/xmlns/sca/values/0.9"

        name="org.apache.servicemix.sca.bigbank">

    <entryPoint name="AccountService">
        <interface.java interface="org.apache.servicemix.sca.bigbank.account.AccountService"/>
        <interface.wsdl interface="http://sca.servicemix.apache.org/Bigbank/Account#AccountService"/>
        <binding.jbi port="http://sca.servicemix.apache.org/Bigbank/Account/AccountService/AccountServiceJBI"/>
        <reference>AccountServiceComponent</reference>
    </entryPoint>

    <component name="AccountServiceComponent">
        <implementation.java class="org.apache.servicemix.sca.bigbank.account.AccountServiceImpl"/>
        <properties>
            <v:currency>EURO</v:currency>
        </properties>
        <references>
            <v:accountDataService>AccountDataServiceComponent</v:accountDataService>
            <v:stockQuoteService>StockQuoteService</v:stockQuoteService>
        </references>
    </component>

    <component name="AccountDataServiceComponent">
        <implementation.java class="org.apache.servicemix.sca.bigbank.accountdata.AccountDataServiceImpl"/>
    </component>

    <externalService name="StockQuoteService">
        <interface.java interface="org.apache.servicemix.sca.bigbank.stockquote.StockQuoteService"/>
        <binding.jbi port="http://www.quickstockquote.com/StockQuoteService/StockQuoteServiceJBI"/>
    </externalService>
    
    <import.wsdl
		location="org/apache/servicemix/sca/bigbank/account/AccountService.wsdl"
		namespace="http://sca.servicemix.apache.org/Bigbank/Account" />

</module>
	
