<?xml version="1.0"?>
<!--
  ~ Licensed to the Apache Software Foundation (ASF) under one
  ~ or more contributor license agreements.  See the NOTICE file
  ~ distributed with this work for additional information
  ~ regarding copyright ownership.  The ASF licenses this file
  ~ to you under the Apache License, Version 2.0 (the
  ~ "License"); you may not use this file except in compliance
  ~ with the License.  You may obtain a copy of the License at
  ~
  ~    http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing,
  ~ software distributed under the License is distributed on an
  ~ "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  ~ KIND, either express or implied.  See the License for the
  ~ specific language governing permissions and limitations
  ~ under the License.
  -->
<definitions name="Pong"
        targetNamespace="http://tuscany.apache.org/implementation/bpel/example/pong.wsdl"
        xmlns:tns="http://tuscany.apache.org/implementation/bpel/example/pong.wsdl"
        xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
        xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
        xmlns="http://schemas.xmlsoap.org/wsdl/">

    <types>
        <schema targetNamespace="http://tuscany.apache.org/implementation/bpel/example/pong.wsdl"
                xmlns="http://www.w3.org/2001/XMLSchema">
            <element name="PongRequest">
                <complexType>
                    <all>
                        <element name="text" type="string"/>
                    </all>
                </complexType>
            </element>
            <element name="PongResponse">
                <complexType>
                    <all>
                        <element name="text" type="string"/>
                    </all>
                </complexType>
            </element>
        </schema>
    </types>

    <message name="PongRequest">
        <part name="body" element="tns:PongRequest"/>
    </message>

    <message name="PongResponse">
        <part name="body" element="tns:PongResponse"/>
    </message>

    <portType name="PongPortType">
        <operation name="Pong">
            <input message="tns:PongRequest"/>
            <output message="tns:PongResponse"/>
        </operation>
    </portType>

    <binding name="PongSoapBinding" type="tns:PongPortType">
	    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="Pong">
            <soap:operation soapAction=""/>
            <input name="PongRequest">
                <soap:body use="literal"/>
            </input>
            <output name="PongResponse">
                <soap:body use="literal"/>
            </output>
        </operation>
	</binding>
    
    <service name="PongService">
		<port name="PongPort" binding="tns:PongSoapBinding">
     		<soap:address location="http://localhost:8085/ode/processes/pong"/>
		</port>
    </service>    
    
    <plnk:partnerLinkType name="PongPartnerLinkType">
        <plnk:role name="Provider" portType="tns:PongPortType"/>
    </plnk:partnerLinkType>
</definitions>
