package org.apache.tuscany.sca.binding.corba.testing.arrays_unions;


/**
* org/apache/tuscany/sca/binding/corba/testing/arrays_unions/TestStruct.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from arrays_unions.idl
* niedziela, 17 sierpieñ 2008 15:45:39 CEST
*/

public final class TestStruct implements org.omg.CORBA.portable.IDLEntity
{
  public String oneDimArray[] = null;
  public int twoDimArray[][] = null;
  public float threeDimArray[][][] = null;

  public TestStruct ()
  {
  } // ctor

  public TestStruct (String[] _oneDimArray, int[][] _twoDimArray, float[][][] _threeDimArray)
  {
    oneDimArray = _oneDimArray;
    twoDimArray = _twoDimArray;
    threeDimArray = _threeDimArray;
  } // ctor

} // class TestStruct
