/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.apache.tuscany.sca.binding.corba.testing.enums;

/**
* org/apache/tuscany/sca/binding/corba/testing/enums/Color.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from enums.idl
* czwartek, 19 czerwiec 2008 15:46:10 CEST
*/

public class Color implements org.omg.CORBA.portable.IDLEntity {
    private int __value;
    private static int __size = 3;
    private static org.apache.tuscany.sca.binding.corba.testing.enums.Color[] __array =
        new org.apache.tuscany.sca.binding.corba.testing.enums.Color[__size];

    public static final int _red = 0;
    public static final org.apache.tuscany.sca.binding.corba.testing.enums.Color red =
        new org.apache.tuscany.sca.binding.corba.testing.enums.Color(_red);
    public static final int _yellow = 1;
    public static final org.apache.tuscany.sca.binding.corba.testing.enums.Color yellow =
        new org.apache.tuscany.sca.binding.corba.testing.enums.Color(_yellow);
    public static final int _green = 2;
    public static final org.apache.tuscany.sca.binding.corba.testing.enums.Color green =
        new org.apache.tuscany.sca.binding.corba.testing.enums.Color(_green);

    public int value() {
        return __value;
    }

    public static org.apache.tuscany.sca.binding.corba.testing.enums.Color from_int(int value) {
        if (value >= 0 && value < __size)
            return __array[value];
        else
            throw new org.omg.CORBA.BAD_PARAM();
    }

    protected Color(int value) {
        __value = value;
        __array[__value] = this;
    }
} // class Color
