
package com.tuscanyscatours.payment;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Payment", targetNamespace = "http://www.tuscanyscatours.com/Payment/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Payment {


    /**
     * 
     * @param amount
     * @param customerId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.tuscanyscatours.com/Payment/makePayment")
    @WebResult(name = "Status", targetNamespace = "")
    @RequestWrapper(localName = "makePaymentMember", targetNamespace = "http://www.tuscanyscatours.com/Payment/", className = "com.tuscanyscatours.payment.MakePaymentMemberType")
    @ResponseWrapper(localName = "makePaymentMemberResponse", targetNamespace = "http://www.tuscanyscatours.com/Payment/", className = "com.tuscanyscatours.payment.MakePaymentMemberResponseType")
    public String makePaymentMember(
        @WebParam(name = "CustomerId", targetNamespace = "")
        String customerId,
        @WebParam(name = "Amount", targetNamespace = "")
        float amount);

}
