<?xml version="1.0" encoding="UTF-8"?>
<!--
  Copyright (c) 2005 BEA Sytems Inc.
  Copyright (c) 2005 International Business Machines

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
 -->
<module xmlns="http://www.osoa.org/xmlns/sca/0.9" xmlns:v="http://www.osoa.org/xmlns/sca/values/0.9"
        name="testModule">

    <import.wsdl location="wsdl/helloworld.wsdl" namespace="http://helloworldaxis.samples.tuscany.apache.org"/>
    <import.sdo wsdlLocation="wsdl/helloworld.wsdl"/>

    <entryPoint name="HelloWorldService">
        <interface.wsdl interface="http://helloworldaxis.samples.tuscany.apache.org#HelloWorldServiceImpl"/>
        <binding.ws port="http://helloworldaxis.samples.tuscany.apache.org#helloworld"/>
        <reference>HelloWorld/HelloWorldService</reference>
    </entryPoint>

    <component name="HelloWorld">
        <implementation.java class="org.apache.tuscany.tomcat.integration.HelloWorldImpl"/>
    </component>

</module>
