/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.    
 */

package org.apache.tuscany.sca.binding.corba.testing.exceptions.CalcPackage;

/**
* org/apache/tuscany/sca/binding/corba/testing/exceptions/CalcPackage/NotSupported.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from exceptions.idl
* sobota, 7 czerwiec 2008 16:12:31 CEST
*/

public final class NotSupported extends org.omg.CORBA.UserException {
    public String info = null;

    public NotSupported() {
        super(NotSupportedHelper.id());
    } // ctor

    public NotSupported(String _info) {
        super(NotSupportedHelper.id());
        info = _info;
    } // ctor

    public NotSupported(String $reason, String _info) {
        super(NotSupportedHelper.id() + "  " + $reason);
        info = _info;
    } // ctor

} // class NotSupported
