
package com.tuscanyscatours.emailgateway;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "EmailGateway", targetNamespace = "http://www.tuscanyscatours.com/EmailGateway/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmailGateway {


    /**
     * 
     * @param email
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.tuscanyscatours.com/EmailGateway/sendEmail")
    @WebResult(name = "Status", targetNamespace = "")
    @RequestWrapper(localName = "sendEmail", targetNamespace = "http://www.tuscanyscatours.com/EmailGateway/", className = "com.tuscanyscatours.emailgateway.SendEmailType")
    @ResponseWrapper(localName = "sendEmailResponse", targetNamespace = "http://www.tuscanyscatours.com/EmailGateway/", className = "com.tuscanyscatours.emailgateway.SendEmailResponseType")
    public String sendEmail(
        @WebParam(name = "Email", targetNamespace = "")
        EmailType email);

}
