<?xml version="1.0" encoding="UTF-8"?>
<!--
  Copyright (c) 2005 The Apache Software Foundation or its licensors, as applicable.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
 -->
<ecore:EPackage xmi:version="2.0"
                xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="addressing"
                nsURI="http://schemas.xmlsoap.org/ws/2004/08/addressing" nsPrefix="wsa">
    <eClassifiers xsi:type="ecore:EClass" name="AttributedQName">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="name" value="AttributedQName"/>
            <details key="kind" value="simple"/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//QName">
            <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
                <details key="name" value=":0"/>
                <details key="kind" value="simple"/>
            </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="anyAttribute" unique="false"
                             upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFeatureMapEntry">
            <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
                <details key="kind" value="attributeWildcard"/>
                <details key="wildcards" value="##other"/>
                <details key="name" value=":1"/>
                <details key="processing" value="lax"/>
            </eAnnotations>
        </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AttributedURI">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="name" value="AttributedURI"/>
            <details key="kind" value="simple"/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//AnyURI">
            <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
                <details key="name" value=":0"/>
                <details key="kind" value="simple"/>
            </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="anyAttribute" unique="false"
                             upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFeatureMapEntry">
            <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
                <details key="kind" value="attributeWildcard"/>
                <details key="wildcards" value="##other"/>
                <details key="name" value=":1"/>
                <details key="processing" value="lax"/>
            </eAnnotations>
        </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DocumentRoot">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="name" value=""/>
            <details key="kind" value="mixed"/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="mixed" unique="false" upperBound="-1"
                             eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFeatureMapEntry">
            <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
                <details key="kind" value="elementWildcard"/>
                <details key="name" value=":mixed"/>
            </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="xMLNSPrefixMap" upperBound="-1"
                             eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStringToStringMapEntry"
                             transient="true" containment="true" resolveProxies="false">
            <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
                <details key="kind" value="attribute"/>
                <details key="name" value="xmlns:prefix"/>
            </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="xSISchemaLocation" upperBound="-1"
                             eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStringToStringMapEntry"
                             transient="true" containment="true" resolveProxies="false">
            <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
                <details key="kind" value="attribute"/>
                <details key="name" value="xsi:schemaLocation"/>
            </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="action" upperBound="-2"
                             eType="#//AttributedURI" volatile="true" transient="true" derived="true" containment="true"
                             resolveProxies="false">
            <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
                <details key="kind" value="element"/>
                <details key="name" value="Action"/>
                <details key="namespace" value="##targetNamespace"/>
            </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="endpointReference" upperBound="-2"
                             eType="#//EndpointReference" volatile="true" transient="true" derived="true"
                             containment="true" resolveProxies="false">
            <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
                <details key="kind" value="element"/>
                <details key="name" value="EndpointReference"/>
                <details key="namespace" value="##targetNamespace"/>
            </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="faultTo" upperBound="-2"
                             eType="#//EndpointReference" volatile="true" transient="true" derived="true"
                             containment="true" resolveProxies="false">
            <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
                <details key="kind" value="element"/>
                <details key="name" value="FaultTo"/>
                <details key="namespace" value="##targetNamespace"/>
            </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="from" upperBound="-2" eType="#//EndpointReference"
                             volatile="true" transient="true" derived="true" containment="true" resolveProxies="false">
            <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
                <details key="kind" value="element"/>
                <details key="name" value="From"/>
                <details key="namespace" value="##targetNamespace"/>
            </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="messageID" upperBound="-2"
                             eType="#//AttributedURI" volatile="true" transient="true" derived="true" containment="true"
                             resolveProxies="false">
            <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
                <details key="kind" value="element"/>
                <details key="name" value="MessageID"/>
                <details key="namespace" value="##targetNamespace"/>
            </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="relatesTo" upperBound="-2"
                             eType="#//Relationship" volatile="true" transient="true" derived="true" containment="true"
                             resolveProxies="false">
            <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
                <details key="kind" value="element"/>
                <details key="name" value="RelatesTo"/>
                <details key="namespace" value="##targetNamespace"/>
            </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="replyAfter" upperBound="-2"
                             eType="#//ReplyAfter" volatile="true" transient="true" derived="true" containment="true"
                             resolveProxies="false">
            <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
                <details key="kind" value="element"/>
                <details key="name" value="ReplyAfter"/>
                <details key="namespace" value="##targetNamespace"/>
            </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="replyTo" upperBound="-2"
                             eType="#//EndpointReference" volatile="true" transient="true" derived="true"
                             containment="true" resolveProxies="false">
            <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
                <details key="kind" value="element"/>
                <details key="name" value="ReplyTo"/>
                <details key="namespace" value="##targetNamespace"/>
            </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="to" upperBound="-2" eType="#//AttributedURI"
                             volatile="true" transient="true" derived="true" containment="true" resolveProxies="false">
            <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
                <details key="kind" value="element"/>
                <details key="name" value="To"/>
                <details key="namespace" value="##targetNamespace"/>
            </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="action1" unique="false"
                             eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//AnyURI">
            <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
                <details key="kind" value="attribute"/>
                <details key="name" value="Action"/>
                <details key="namespace" value="##targetNamespace"/>
            </eAnnotations>
        </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EndpointReference">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="name" value="EndpointReferenceType"/>
            <details key="kind" value="elementOnly"/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="addressElement" lowerBound="1"
                             eType="#//AttributedURI" containment="true" resolveProxies="false">
            <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
                <details key="kind" value="element"/>
                <details key="name" value="Address"/>
                <details key="namespace" value="##targetNamespace"/>
            </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="referencePropertiesElement"
                             eType="#//ReferenceProperties" containment="true" resolveProxies="false">
            <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
                <details key="kind" value="element"/>
                <details key="name" value="ReferenceProperties"/>
                <details key="namespace" value="##targetNamespace"/>
            </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="referenceParametersElement"
                             eType="#//ReferenceParameters" containment="true" resolveProxies="false">
            <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
                <details key="kind" value="element"/>
                <details key="name" value="ReferenceParameters"/>
                <details key="namespace" value="##targetNamespace"/>
            </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="portTypeElement" eType="#//AttributedQName"
                             containment="true" resolveProxies="false">
            <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
                <details key="kind" value="element"/>
                <details key="name" value="PortType"/>
                <details key="namespace" value="##targetNamespace"/>
            </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="serviceNameElement" eType="#//ServiceName"
                             containment="true" resolveProxies="false">
            <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
                <details key="kind" value="element"/>
                <details key="name" value="ServiceName"/>
                <details key="namespace" value="##targetNamespace"/>
            </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="any" unique="false" upperBound="-1"
                             eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFeatureMapEntry">
            <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
                <details key="documentation" value="&#xD;&#xA;&#x9;&#x9;&#x9;&#x9;&#x9; If &quot;Policy&quot; elements from namespace &quot;http://schemas.xmlsoap.org/ws/2002/12/policy#policy&quot; are used, they must appear first (before any extensibility elements).&#xD;&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;"/>
            </eAnnotations>
            <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
                <details key="kind" value="elementWildcard"/>
                <details key="wildcards" value="##other"/>
                <details key="name" value=":5"/>
                <details key="processing" value="lax"/>
            </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="anyAttribute" unique="false"
                             upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFeatureMapEntry">
            <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
                <details key="kind" value="attributeWildcard"/>
                <details key="wildcards" value="##other"/>
                <details key="name" value=":6"/>
                <details key="processing" value="lax"/>
            </eAnnotations>
        </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="FaultSubcodeValues" instanceClassName="java.lang.Object">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="name" value="FaultSubcodeValues"/>
            <details key="baseType" value="http://www.eclipse.org/emf/2003/XMLType#QName"/>
            <details key="enumeration" value="wsa:InvalidMessageInformationHeader wsa:MessageInformationHeaderRequired wsa:DestinationUnreachable wsa:ActionNotSupported wsa:EndpointUnavailable"/>
        </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ReferenceParameters">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="name" value="ReferenceParametersType"/>
            <details key="kind" value="elementOnly"/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="any" unique="false" upperBound="-1"
                             eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFeatureMapEntry">
            <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
                <details key="kind" value="elementWildcard"/>
                <details key="wildcards" value="##any"/>
                <details key="name" value=":0"/>
                <details key="processing" value="lax"/>
            </eAnnotations>
        </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ReferenceProperties">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="name" value="ReferencePropertiesType"/>
            <details key="kind" value="elementOnly"/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="any" unique="false" upperBound="-1"
                             eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFeatureMapEntry">
            <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
                <details key="kind" value="elementWildcard"/>
                <details key="wildcards" value="##any"/>
                <details key="name" value=":0"/>
                <details key="processing" value="lax"/>
            </eAnnotations>
        </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Relationship">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="name" value="Relationship"/>
            <details key="kind" value="simple"/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//AnyURI">
            <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
                <details key="name" value=":0"/>
                <details key="kind" value="simple"/>
            </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="relationshipType" unique="false"
                             eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//QName">
            <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
                <details key="kind" value="attribute"/>
                <details key="name" value="RelationshipType"/>
            </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="anyAttribute" unique="false"
                             upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFeatureMapEntry">
            <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
                <details key="kind" value="attributeWildcard"/>
                <details key="wildcards" value="##other"/>
                <details key="name" value=":2"/>
                <details key="processing" value="lax"/>
            </eAnnotations>
        </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="RelationshipTypeValues" instanceClassName="java.lang.Object">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="name" value="RelationshipTypeValues"/>
            <details key="baseType" value="http://www.eclipse.org/emf/2003/XMLType#QName"/>
            <details key="enumeration" value="wsa:Reply"/>
        </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ReplyAfter">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="name" value="ReplyAfterType"/>
            <details key="kind" value="simple"/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//NonNegativeInteger">
            <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
                <details key="name" value=":0"/>
                <details key="kind" value="simple"/>
            </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="anyAttribute" unique="false"
                             upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFeatureMapEntry">
            <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
                <details key="kind" value="attributeWildcard"/>
                <details key="wildcards" value="##other"/>
                <details key="name" value=":1"/>
                <details key="processing" value="strict"/>
            </eAnnotations>
        </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ServiceName">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="name" value="ServiceNameType"/>
            <details key="kind" value="simple"/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//QName">
            <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
                <details key="name" value=":0"/>
                <details key="kind" value="simple"/>
            </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="portName" unique="false"
                             eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//NCName">
            <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
                <details key="kind" value="attribute"/>
                <details key="name" value="PortName"/>
            </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="anyAttribute" unique="false"
                             upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFeatureMapEntry">
            <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
                <details key="kind" value="attributeWildcard"/>
                <details key="wildcards" value="##other"/>
                <details key="name" value=":2"/>
                <details key="processing" value="lax"/>
            </eAnnotations>
        </eStructuralFeatures>
    </eClassifiers>
</ecore:EPackage>
