/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.    
 */

package calculator.idl;


/**
* calculator/idl/_CalculatorCORBAServiceImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CalculatorCORBA.idl
* ¶roda, 15 pa¼dziernik 2008 16:02:31 CEST
*/

public abstract class _CalculatorCORBAServiceImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements calculator.idl.CalculatorCORBAService, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _CalculatorCORBAServiceImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("add", new java.lang.Integer (0));
    _methods.put ("subtract", new java.lang.Integer (1));
    _methods.put ("multiply", new java.lang.Integer (2));
    _methods.put ("divide", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // calculator/idl/CalculatorCORBAService/add
       {
         double arg1 = in.read_double ();
         double arg2 = in.read_double ();
         double $result = (double)0;
         $result = this.add (arg1, arg2);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 1:  // calculator/idl/CalculatorCORBAService/subtract
       {
         double arg1 = in.read_double ();
         double arg2 = in.read_double ();
         double $result = (double)0;
         $result = this.subtract (arg1, arg2);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 2:  // calculator/idl/CalculatorCORBAService/multiply
       {
         double arg1 = in.read_double ();
         double arg2 = in.read_double ();
         double $result = (double)0;
         $result = this.multiply (arg1, arg2);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 3:  // calculator/idl/CalculatorCORBAService/divide
       {
         double arg1 = in.read_double ();
         double arg2 = in.read_double ();
         double $result = (double)0;
         $result = this.divide (arg1, arg2);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:calculator/idl/CalculatorCORBAService:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _CalculatorCORBAServiceImplBase
