<?xml version="1.0" encoding="UTF-8"?>
<!--
    * Licensed to the Apache Software Foundation (ASF) under one
    * or more contributor license agreements.  See the NOTICE file
    * distributed with this work for additional information
    * regarding copyright ownership.  The ASF licenses this file
    * to you under the Apache License, Version 2.0 (the
    * "License"); you may not use this file except in compliance
    * with the License.  You may obtain a copy of the License at
    * 
    *   http://www.apache.org/licenses/LICENSE-2.0
    * 
    * Unless required by applicable law or agreed to in writing,
    * software distributed under the License is distributed on an
    * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
    * KIND, either express or implied.  See the License for the
    * specific language governing permissions and limitations
    * under the License.    
-->
<wsdl:definitions name="OrderService"
	targetNamespace="http://OrderService/OrderService/rootwsdl" xmlns:im="http://OrderService/OrderService/importwsdl"
	xmlns:tns="http://OrderService/OrderService/rootwsdl" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:this="http://OrderService/OrderService/rootwsdl">
	<wsdl:import location="ImportedOrderService.wsdl" namespace="http://OrderService/OrderService/importwsdl" />
	<wsdl:binding name="OrderServiceHttpBinding"
		type="im:OrderService">
		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="retrieveOrder">
			<soap:operation soapAction="" />
			<wsdl:input name="retrieveOrderRequest">
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output name="retrieveOrderResponse">
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="writeOrder">
			<soap:operation soapAction="" />
			<wsdl:input name="writeOrderRequest">
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output name="writeOrderResponse">
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="updateOrderStatus">
			<soap:operation soapAction="" />
			<wsdl:input name="updateOrderStatusRequest">
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output name="updateOrderStatusResponse">
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="OrderServiceHttpService">
		<wsdl:port binding="this:OrderServiceHttpBinding"
			name="OrderServiceHttpPort">
			<soap:address
				location="http://localhost:9080/OrderService.WSBindingWeb/sca/OrderServiceExport" />
		</wsdl:port>
	</wsdl:service>

</wsdl:definitions>
