<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions targetNamespace="http://swanandmokashi.com" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
    <wsdl:import namespace="http://swanandmokashi.com"
        location="http://www.swanandmokashi.com/HomePage/WebServices/StockQuotes.asmx?WSDL" />
</wsdl:definitions>