<?xml version="1.0" encoding="UTF-8"?>
<!--
 *  Copyright (c) 2005 The Apache Software Foundation or its licensors, as applicable.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 -->
<ecore:EPackage xmi:version="2.0"
                xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="config"
                nsURI="http://org.apache.tuscany/xmlns/model/config/0.9" nsPrefix="config">
    <eClassifiers xsi:type="ecore:EClass" name="DocumentRoot">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="name" value=""/>
            <details key="kind" value="mixed"/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="mixed" unique="false" upperBound="-1"
                             eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFeatureMapEntry">
            <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
                <details key="kind" value="elementWildcard"/>
                <details key="name" value=":mixed"/>
            </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="xMLNSPrefixMap" upperBound="-1"
                             eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStringToStringMapEntry"
                             transient="true" containment="true" resolveProxies="false">
            <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
                <details key="kind" value="attribute"/>
                <details key="name" value="xmlns:prefix"/>
            </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="xSISchemaLocation" upperBound="-1"
                             eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStringToStringMapEntry"
                             transient="true" containment="true" resolveProxies="false">
            <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
                <details key="kind" value="attribute"/>
                <details key="name" value="xsi:schemaLocation"/>
            </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="modelConfiguration" upperBound="-2"
                             eType="#//ModelConfiguration" volatile="true" transient="true" derived="true"
                             containment="true" resolveProxies="false">
            <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
                <details key="kind" value="element"/>
                <details key="name" value="modelConfiguration"/>
                <details key="namespace" value="##targetNamespace"/>
            </eAnnotations>
        </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DynamicPackage">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="name" value="DynamicPackage"/>
            <details key="kind" value="elementOnly"/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="any" unique="false" upperBound="-1"
                             eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFeatureMapEntry">
            <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
                <details key="kind" value="elementWildcard"/>
                <details key="wildcards" value="##other"/>
                <details key="name" value=":0"/>
                <details key="processing" value="lax"/>
            </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="loaderClassName" unique="false"
                             eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String">
            <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
                <details key="kind" value="attribute"/>
                <details key="name" value="loaderClassName"/>
            </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" unique="false"
                             eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String">
            <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
                <details key="kind" value="attribute"/>
                <details key="name" value="location"/>
            </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="preLoad" unique="false"
                             eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"
                             unsettable="true">
            <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
                <details key="kind" value="attribute"/>
                <details key="name" value="preLoad"/>
            </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="uri" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String">
            <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
                <details key="kind" value="attribute"/>
                <details key="name" value="uri"/>
            </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="anyAttribute" unique="false"
                             upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFeatureMapEntry">
            <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
                <details key="kind" value="attributeWildcard"/>
                <details key="wildcards" value="##any"/>
                <details key="name" value=":5"/>
                <details key="processing" value="lax"/>
            </eAnnotations>
        </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DynamicPackageLoader">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="name" value="DynamicPackageLoader"/>
            <details key="kind" value="elementOnly"/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="any" unique="false" upperBound="-1"
                             eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFeatureMapEntry">
            <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
                <details key="kind" value="elementWildcard"/>
                <details key="wildcards" value="##other"/>
                <details key="name" value=":0"/>
                <details key="processing" value="lax"/>
            </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="className" unique="false"
                             eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String">
            <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
                <details key="kind" value="attribute"/>
                <details key="name" value="className"/>
            </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="extension" unique="false"
                             eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String">
            <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
                <details key="kind" value="attribute"/>
                <details key="name" value="extension"/>
            </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="protocol" unique="false"
                             eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String">
            <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
                <details key="kind" value="attribute"/>
                <details key="name" value="protocol"/>
            </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="anyAttribute" unique="false"
                             upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFeatureMapEntry">
            <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
                <details key="kind" value="attributeWildcard"/>
                <details key="wildcards" value="##any"/>
                <details key="name" value=":4"/>
                <details key="processing" value="lax"/>
            </eAnnotations>
        </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="GeneratedPackage">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="name" value="GeneratedPackage"/>
            <details key="kind" value="elementOnly"/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="any" unique="false" upperBound="-1"
                             eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFeatureMapEntry">
            <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
                <details key="kind" value="elementWildcard"/>
                <details key="wildcards" value="##other"/>
                <details key="name" value=":0"/>
                <details key="processing" value="lax"/>
            </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="packageClassName" unique="false"
                             eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String">
            <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
                <details key="kind" value="attribute"/>
                <details key="name" value="packageClassName"/>
            </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="preLoad" unique="false"
                             eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"
                             unsettable="true">
            <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
                <details key="kind" value="attribute"/>
                <details key="name" value="preLoad"/>
            </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="uri" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String">
            <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
                <details key="kind" value="attribute"/>
                <details key="name" value="uri"/>
            </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="anyAttribute" unique="false"
                             upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFeatureMapEntry">
            <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
                <details key="kind" value="attributeWildcard"/>
                <details key="wildcards" value="##any"/>
                <details key="name" value=":4"/>
                <details key="processing" value="lax"/>
            </eAnnotations>
        </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ModelConfiguration">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="name" value="ModelConfiguration"/>
            <details key="kind" value="elementOnly"/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="generatedPackages" upperBound="-1"
                             eType="#//GeneratedPackage" containment="true" resolveProxies="false">
            <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
                <details key="kind" value="element"/>
                <details key="name" value="generatedPackage"/>
            </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="dynamicPackages" upperBound="-1"
                             eType="#//DynamicPackage" containment="true" resolveProxies="false">
            <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
                <details key="kind" value="element"/>
                <details key="name" value="dynamicPackage"/>
            </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="dynamicPackageLoaders"
                             upperBound="-1" eType="#//DynamicPackageLoader" containment="true" resolveProxies="false">
            <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
                <details key="kind" value="element"/>
                <details key="name" value="dynamicPackageLoader"/>
            </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="uriMappings" upperBound="-1"
                             eType="#//URIMapping" containment="true" resolveProxies="false">
            <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
                <details key="kind" value="element"/>
                <details key="name" value="uriMapping"/>
            </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="resourceFactories" upperBound="-1"
                             eType="#//ResourceFactory" containment="true" resolveProxies="false">
            <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
                <details key="kind" value="element"/>
                <details key="name" value="resourceFactory"/>
            </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="any" unique="false" upperBound="-1"
                             eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFeatureMapEntry">
            <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
                <details key="kind" value="elementWildcard"/>
                <details key="wildcards" value="##other"/>
                <details key="name" value=":5"/>
                <details key="processing" value="lax"/>
            </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="anyAttribute" unique="false"
                             upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFeatureMapEntry">
            <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
                <details key="kind" value="attributeWildcard"/>
                <details key="wildcards" value="##any"/>
                <details key="name" value=":6"/>
                <details key="processing" value="lax"/>
            </eAnnotations>
        </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ResourceFactory">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="name" value="ResourceFactory"/>
            <details key="kind" value="elementOnly"/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="any" unique="false" upperBound="-1"
                             eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFeatureMapEntry">
            <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
                <details key="kind" value="elementWildcard"/>
                <details key="wildcards" value="##other"/>
                <details key="name" value=":0"/>
                <details key="processing" value="lax"/>
            </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="className" unique="false"
                             eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String">
            <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
                <details key="kind" value="attribute"/>
                <details key="name" value="className"/>
            </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="extension" unique="false"
                             eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String">
            <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
                <details key="kind" value="attribute"/>
                <details key="name" value="extension"/>
            </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="protocol" unique="false"
                             eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String">
            <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
                <details key="kind" value="attribute"/>
                <details key="name" value="protocol"/>
            </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="anyAttribute" unique="false"
                             upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFeatureMapEntry">
            <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
                <details key="kind" value="attributeWildcard"/>
                <details key="wildcards" value="##any"/>
                <details key="name" value=":4"/>
                <details key="processing" value="lax"/>
            </eAnnotations>
        </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="URIMapping">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="name" value="URIMapping"/>
            <details key="kind" value="elementOnly"/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="any" unique="false" upperBound="-1"
                             eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFeatureMapEntry">
            <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
                <details key="kind" value="elementWildcard"/>
                <details key="wildcards" value="##other"/>
                <details key="name" value=":0"/>
                <details key="processing" value="lax"/>
            </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" unique="false"
                             eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String">
            <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
                <details key="kind" value="attribute"/>
                <details key="name" value="source"/>
            </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="target" unique="false"
                             eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String">
            <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
                <details key="kind" value="attribute"/>
                <details key="name" value="target"/>
            </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="anyAttribute" unique="false"
                             upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFeatureMapEntry">
            <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
                <details key="kind" value="attributeWildcard"/>
                <details key="wildcards" value="##any"/>
                <details key="name" value=":3"/>
                <details key="processing" value="lax"/>
            </eAnnotations>
        </eStructuralFeatures>
    </eClassifiers>
</ecore:EPackage>
