package org.apache.tuscany.databinding.jaxb.fault;

import javax.xml.ws.WebFault;

/**
 * This class was generated by the JAXWS SI. JAX-WS RI 2.1-02/02/2007 09:55
 * AM(vivekp)-FCS Generated source version: 2.1
 */
@WebFault(name = "InvalidSymbolFault", targetNamespace = "http://www.example.com/stock")
public class InvalidSymbolFault_Exception extends Exception {

    /**
     * Java type that goes as soapenv:Fault detail element.
     */
    private InvalidSymbolFault faultInfo;

    /**
     * @param faultInfo
     * @param message
     */
    public InvalidSymbolFault_Exception(String message, InvalidSymbolFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * @param faultInfo
     * @param message
     * @param cause
     */
    public InvalidSymbolFault_Exception(String message, InvalidSymbolFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * @return returns fault bean:
     *         org.apache.tuscany.sca.test.exceptions.impl.jaxb.InvalidSymbolFault
     */
    public InvalidSymbolFault getFaultInfo() {
        return faultInfo;
    }

}
