<?xml version="1.0" encoding="UTF-8"?>
<!--
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.    
-->
<!--definitions
     name="EmpFlexFieldService"
     targetNamespace="/model/common/"
     xmlns="http://schemas.xmlsoap.org/wsdl/"
     xmlns:tns="/model/common/"
     xmlns:errors="http://xmlns.oracle.com/adf/svc/errors/"
     xmlns:types="/model/common/types/"
     xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    -->
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
				  xmlns:ns0="http://example.com"
				  xmlns:ns2="/model/common/types/"
				  xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
				  xmlns:http="http://schemas.xmlsoap.org/wsdl/http/"
				  xmlns:ns1="http://example.com/xsd"
				  xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl"
				  xmlns:xs="http://www.w3.org/2001/XMLSchema"
				  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
				  targetNamespace="/model/common/"
				  xmlns:tns="/model/common/">
    <wsdl:types>
        <xs:schema>
            <import namespace="/model/common/types/" schemaLocation="ExampleServiceTypes.xsd"/>
        </xs:schema>
        <xs:schema xmlns:ns="http://example.com" attributeFormDefault="qualified" elementFormDefault="qualified" targetNamespace="http://example.com">
            <xs:element name="BusinessException">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element minOccurs="0" name="BusinessException" nillable="true" type="ns1:BusinessException"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:schema>
        <xs:schema xmlns:ax21="http://example.com/xsd" attributeFormDefault="qualified" elementFormDefault="qualified" targetNamespace="http://example.com/xsd">
            <xs:complexType name="BusinessException">
                <xs:complexContent>
                    <xs:extension base="tns:Exception">
                        <xs:sequence/>
                    </xs:extension>
                </xs:complexContent>
            </xs:complexType>
        </xs:schema>
    </wsdl:types>
    <wsdl:message name="helloRequest">
        <wsdl:part name="parameters" element="ns2:hello"/>
    </wsdl:message>
    <wsdl:message name="helloResponse">
        <wsdl:part name="parameters" element="ns2:helloResponse"/>
    </wsdl:message>
    <wsdl:message name="BusinessException">
        <wsdl:part name="parameters" element="ns0:BusinessException"/>
    </wsdl:message>
    <wsdl:portType name="ExampleServicePortType">
        <wsdl:operation name="hello">
            <wsdl:input message="tns:helloRequest" wsaw:Action="urn:hello"/>
            <wsdl:output message="tns:helloResponse" wsaw:Action="urn:helloResponse"/>
            <wsdl:fault message="tns:BusinessException" name="BusinessException" wsaw:Action="urn:helloBusinessException"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="ExampleServiceSOAP11Binding" type="tns:ExampleServicePortType">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
        <wsdl:operation name="hello">
            <soap:operation soapAction="urn:hello" style="document"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
            <wsdl:fault name="BusinessException">
                <soap:fault use="literal" name="BusinessException"/>
            </wsdl:fault>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:binding name="ExampleServiceSOAP12Binding" type="tns:ExampleServicePortType">
        <soap12:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
        <wsdl:operation name="hello">
            <soap12:operation soapAction="urn:hello" style="document"/>
            <wsdl:input>
                <soap12:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap12:body use="literal"/>
            </wsdl:output>
            <wsdl:fault name="BusinessException">
                <soap12:fault use="literal" name="BusinessException"/>
            </wsdl:fault>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:binding name="ExampleServiceHttpBinding" type="tns:ExampleServicePortType">
        <http:binding verb="POST"/>
        <wsdl:operation name="hello">
            <http:operation location="ExampleService/hello"/>
            <wsdl:input>
                <mime:content type="text/xml" part="hello"/>
            </wsdl:input>
            <wsdl:output>
                <mime:content type="text/xml" part="hello"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="ExampleService">
        <wsdl:port name="ExampleServiceSOAP11port_http" binding="tns:ExampleServiceSOAP11Binding">
            <soap:address location="http://localhost:8085/axis2/services/ExampleService"/>
        </wsdl:port>
        <wsdl:port name="ExampleServiceSOAP12port_http" binding="tns:ExampleServiceSOAP12Binding">
            <soap12:address location="http://localhost:8085/axis2/services/ExampleService"/>
        </wsdl:port>
        <wsdl:port name="ExampleServiceHttpport" binding="tns:ExampleServiceHttpBinding">
            <http:address location="http://localhost:8085/axis2/services/ExampleService"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
