/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.    
 */

/*
 * compile by
 * idlj -fall -oldImplBase arrays_unions.idl
 */

module org {
	module apache {
		module tuscany {
			module sca {
				module binding {
					module corba {
						module testing {
							module arrays_unions {
								
								struct TestStruct {
									string oneDimArray[2];
									long twoDimArray[2][4];
									float threeDimArray[2][4][2];
								};
								
								typedef string StringArray[2][2];
								
								union InnerUnion switch (long) {
									case 1: long x;
									case 2: float y;
								};
								
								union RichUnion switch (long) {
								    case 1: long x;
									case 2: float y;
								    case 3: string z;
								    case 4: InnerUnion iu;
								    default: boolean a;
								};
								
								interface ArraysUnionsTests {
									TestStruct passTestStruct(in TestStruct arg);
									StringArray passStringArray(in StringArray arg);
									RichUnion passRichUnion(in RichUnion arg);
								};
								
							};
						};
					};
				};
			};
		};
	};
};

