/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.    
 */

/*
 * compile by
 * idlj -fall -oldImplBase exceptions.idl
 */

module org {
	module apache {
		module tuscany {
			module sca {
				module binding {
					module corba {
						module testing {
							module exceptions {
								interface Calc {
									struct Arguments {
										double arg1;
										double arg2;
									};
							
									exception DivByZero{ 
										Arguments arguments;
										string info;
									};
									
									exception NotSupported {
										string info;
									};
							
									double div(in double arg1, in double arg2) raises(DivByZero);
									double divForSmallArgs(in double arg1, in double arg2) raises(DivByZero, NotSupported);
								};
							};
						};
					};
				};
			};
		};
	};
};
